modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="compressed_barrels"
version="1.0.0"
displayName="Compressed Barrels"
credits="nano"
displayURL="https://mcreator.net"

[[dependencies.compressed_barrels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




